services:
    settings_manager:
      alias: netbull.settings.settings_manager

    netbull.settings.settings_manager:
        class: NetBull\SettingsBundle\Manager\SettingsManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@netbull.settings.serializer'
            - '%settings_manager.settings%'

    netbull.settings.cached_settings_manager:
        class: NetBull\SettingsBundle\Manager\CachedSettingsManager
        arguments: ['@netbull.settings.settings_manager', ~, ~]

    netbull.settings.serializer_factory:
        class: NetBull\SettingsBundle\Serializer\SerializerFactory

    netbull.settings.serializer:
        class: NetBull\SettingsBundle\Serializer\PhpSerializer
        factory: ['@netbull.settings.serializer_factory', create]
        arguments: ['%settings_manager.serialization%']

    form.type.settings_management:
        class: NetBull\SettingsBundle\Form\Type\SettingsType
        arguments:
            - '%settings_manager.settings%'
        tags:
            - { name: form.type }

    twig.extension.settings_extension:
        class: NetBull\SettingsBundle\Twig\SettingsExtension
        arguments:
            - '@settings_manager'
        tags:
            - { name: twig.extension }
